### ISSUE TITLE
Investigate ways to generate session token

### ISSUE THREAD

**Issue by aprajshekhar** [gamedoora/gamedoora-user-services#14]
**Describe the bug**

- Can we need to generate our own token?
   - If yes, what are the approaches?

**Comment by aprajshekhar** [comment]
We do not need to generate token by ourselves. Using keycloak server, the token can be generated and authenticated.
@picksitquick my suggestion is that we can close this issue.

**Comment by picksitquick** [comment]
Yes, this looks good, we can close this issue for now.
