### ISSUE TITLE
Add APIs to retrieve user related data for Role, Skills, and Projects

### ISSUE THREAD

**Issue by aprajshekhar** [gamedoora/gamedoora-user-services#21]
**Describe the bug**
Current APIs does not provide a way to retrieve associated data at a more granular. Following APIs would be required to help with such a requirement:
1 . Find users by role.
2. Find users by name.
3. Find users by skill.
4. Find roles with a specific skill 
5. List users by skills 

**Additional context**
These APIs would make aggregation easier at proxy level.

**Comment by picksitquick** [comment]
#34 solves this issue
